version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: fh_postgres
    environment:
      POSTGRES_DB: flexible_hours
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "1224:5432"